--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/WolfDen133/WFT
build-by-default: true
branches:
- main
projects:
  WFT:
    path: ""
    icon: "logo.png"
    libs:
      - src: Vecnavium/FormsUI/libFormsUI
        version: ^2.0.0
    lint:
      phpstan: false
...
