---
name: WFT
author: WolfDen133

main: WolfDen133\WFT\WFT

version: 1.3.6
api: 4.10.0

permissions:
  wft.command.use:
    default: op
    description: Allows the use of the wft command

...
